spring.application.name=springbootdemo
coach.name=Zinedine Zidane
coach.age=51
team.name=Real Madrid
# Use wildcard "*" to expose all endpoints
# Can also expose individual endpoints by specifying their names, e.g., "health,info"
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My Spring Boot Application
info.app.description=This is a demo Spring Boot application
info.app.version=1.0.0
