spring.application.name=cruddemo

# JDBC properties 
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Configure api versioning, path-segment is segment positon in the url : https://api/{path}
spring.mvc.apiversion.use.path-segment=1

# Configure Swagger Openapi
# springdoc.swagger-ui.path=/my-ui.html
# springdoc.api-docs.path=/my-api-docs 